### ISSUE TITLE
branching not correctly relocking across sessions

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-branching#17]
Whilst https://github.com/adaptlearning/adapt-contrib-branching/issues/15 has been resolved, there is an issue if a user exits a branched assessment with an incomplete presentation component (works fine if incomplete branched questions). When a user returns in a new browser session, the previous incomplete component is now completed and content is not correctly `_isLocked` (bypassing (https://github.com/adaptlearning/adapt-contrib-core/issues/22), allowing a user to navigate past the assessment to the next article, whether via bookmarking or accessing the page via the menu.

**Comment by oliverfoster** [comment]
Fixed in latest version with addition of presentation component state saves.
