### ISSUE TITLE
Trickle not working

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt-contrib-branching#36]
### Subject of the issue/enhancement/features
I haven't been able to get Trickle working with this extension, despite the Readme saying that it should be supported (assuming v4+). Thought it might be nice to have autoscroll as a feature.

```
  {
    "_id": "b-40",
    "_parentId": "a-10",
    "_type": "block",
    "_classes": "",
    "title": "b-40",
    "displayTitle": "",
    "body": "",
    "_trackingId": 7,
    "_branching": {
      "_isEnabled": true,
      "_containerId": "",
      "__comment": "leave _containerId blank to use the article _id",
      "_correct": "b-45",
      "_partlyCorrect": "b-50",
      "_incorrect": "b-50"
    },
    "_trickle": {
      "_isEnabled": true,
      "_isInherited": false,
      "_autoScroll": true,
      "_scrollDuration": 500,
      "_onChildren": false,
      "_scrollTo": "@block +1",
      "_completionAttribute": "_isInteractionComplete|_isComplete",
      "_button": {
          "_isEnabled": false
      },
      "_stepLocking": {
          "_isEnabled": false,
          "_isCompletionRequired": true,
          "_isLockedOnRevisit": false
      }
  }
 ```

### Your environment
Fresh install of the latest version of Adapt with the latest version of this plugin.

[220728115945_src_course.aat.zip](https://github.com/adaptlearning/adapt-contrib-branching/files/9208544/220728115945_src_course.aat.zip)

**Comment by oliverfoster** [comment]
@simondate can yu try with #38 and https://github.com/adaptlearning/adapt-contrib-trickle/pull/169 please?

**Comment by oliverfoster** [comment]
No response
