### ISSUE TITLE
branching issue

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt-contrib-branching#43]
### Subject of the issue
branching issue

### Your environment
* version (Framework) - 5.28.7
* which browser and its version - Chrome 111.0.5563.65

### Steps to reproduce
enabled branching to course then to article json as below 
 "_branching": {
            "_isEnabled": true,
            "_onChildren": true,
            "_comment": "Leave _start blank to start on the first block in the article",
            "_start": ""
        }
and at block.json as below 
  "_branching": {
        "_containerId": "",
        "__comment": "leave _containerId blank to use the article _id",
        "_correct": "b-115",
        "_partlyCorrect": "",
        "_incorrect": "b-120"
      }

### Expected behaviour
its not working, would it work like if question is correct then it goes to  "_correct": "b-115", and if question is wrong then   "_incorrect": "b-120"  ?

am i making wrong setting ??

### Actual behaviour
block where i added this setting is appearing to the end to page, how it should work, i debug a bit when we submit question then next block is not finding. 

![image](https://user-images.githubusercontent.com/12641875/227482391-065a1a87-e203-435a-82ca-5462fc08ec5c.png)

**Comment by simondate** [comment]
I've just tested on 5.28.7 and wasn't able to use it too. It is working on v5.23.0

These errors appear on page load

<img width="219" alt="chrome_2023-03-26_19-51-57" src="https://user-images.githubusercontent.com/1676635/227794558-28539cf5-06fd-453f-8a67-a312723d4fd7.png">

and this error appears when you try to submit a question that has been set up.

<img width="214" alt="chrome_2023-03-26_19-52-50" src="https://user-images.githubusercontent.com/1676635/227794602-b5003bc2-bd67-4875-8951-b490aae2c5a0.png">

Looking at the code it appears that it now expects some parameters to be passed when creating new blocks.

**Comment by oliverfoster** [comment]
this pr broke it https://github.com/adaptlearning/adapt-contrib-core/commit/d890735268715baae34c448e99613a9708e6ed5a

**Comment by oliverfoster** [comment]
@danielghost could you put that in a separate issue please? It's unrelated.
