### ISSUE TITLE
Branching issue when revisiting

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-branching#56]
### Subject of the issue
When revisiting a course, blocks that have been skipped initially due to a correct answer are displaying.

### Your environment
* Branching v1.2.2
* Spoor v5.9.8
* Framework 5.38.2

### Steps to reproduce
In _course.json_, enable branching:

```
  "_branching": {
    "_isEnabled": true
  }
```

And Spoor:

```
  "_spoor": {
    "_isEnabled": true,
    "_tracking": {
      "_shouldStoreResponses": true,
      "_shouldStoreAttempts": true,
      "_shouldRecordInteractions": true
    },
    "_reporting": {
      "_onTrackingCriteriaMet": "completed",
      "_onAssessmentFailure": "incomplete",
      "_resetStatusOnLanguageChange": false
    }
  },
```

In an **article**, enable branching:

```
    "_branching": {
      "_isEnabled": true,
      "_onChildren": true,
      "_start": ""
    },
```

In the **blocks** for this article, set up branching so that you jump to the last block on the page once you answer correctly. For example, below would be the `_branching` config for the first block `b-300`. If answered incorrectly, it would go to `b-305` (the next question). If answered correctly, it goes to `b-395`.

```
    "_branching": {
      "_containerId": "",
      "_correct": "b-395",
      "_partlyCorrect": "b-305",
      "_incorrect": "b-305"
    },
```
`b-305` would be configured similarly, but answering incorrectly goes to `b-310` (the next question):

```
    "_branching": {
      "_containerId": "",
      "_correct": "b-395",
      "_partlyCorrect": "b-310",
      "_incorrect": "b-310"
    },
```

And so on. Set up a few blocks like this.

Finally, visit the course using the `scorm_test_harness.html` link or in an LMS. Correctly answer the first question in `b-300` so that you can skip the remainder of the blocks on the page (except for the last).

Revisit the page by reloading `scorm_test_harness.html` or exiting and returning to the LMS.

### Expected behaviour
Revisiting and returning to the page should only show the first question (answered correctly) and the last block.

<img src="https://github.com/adaptlearning/adapt-contrib-bookmarking/assets/898168/5c399f49-811f-47a6-8852-5590572596f0" width="300">

### Actual behaviour
The next question block `b-305` is displayed and is incomplete.

<img src="https://github.com/adaptlearning/adapt-contrib-bookmarking/assets/898168/0c5e9976-51ae-40fc-8637-cd1805361bb8" width="300">

### Completion
Note that if you get a full course completion and exit the course, it will be recorded in the LMS (or SCORM Cloud) as "completed". However, revisiting will then make the course "incomplete" since there is new content that must be completed.

**Comment by oliverfoster** [comment]
This is as, on a restored cloned branching mcq, `restoreUserAnswers` is not called appropriately before checking the correctness, such that no restored items have been set to `_isActive` when branching comes to check correctness at `isCorrect` https://github.com/adaptlearning/adapt-contrib-branching/blob/036b75fef296c5e09446ef09dfa3969f29eb695e/js/branchingAlgorithm.js#L4-L16
