### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-branching#57]
### Subject of the enhancement
There are a few areas of the documentation that could be improved on. I'm still compiling a list, but here are a few:

### `_correct`, `incorrect`, `_partlyCorrect` values
1. When left blank, the branching sequence will go to the next available content block.
2. Is `@block+1` a valid value?

### General
1. How should the last block in a sequence be configured? Should it have values for `_correct`, `incorrect`, `_partlyCorrect`, should it have the `_branching` object but not other properties, etc?
2. Can we have multiple branching articles on the same page?

### Presentation components
1. Are presentation components officially supported as part of the branching sequence? They are not specifically mentioned in the docs.
3. What should the values of `_correct`, `incorrect`, `_partlyCorrect` be in presentation components? Empty strings, the same block ID, etc?

### Miscellaneous housekeeping
1. Remove "Framework versions" from _README.md_
2. Fix typo in _pull_request_template.md_ for "udpate"

**Comment by oliverfoster** [comment]
Branching branches with blocks. Components don't have branching values. Block can contain any kind of component. Presentation component only blocks will complete when in view mostly. A block with only presentation components has only a _correct branch as it's impossible to get partly correct or incorrect.

@block+1 is valid only where there is a subsequent block. Is assessment randomisation or banks and branching are used then it's impossible to say which is the last block.
